FROM openjdk:17
MAINTAINER "Ashok Bollepalli <797979>"
COPY target/SpringBoot-CRUD-Operations.jar  /usr/app/
WORKDIR /usr/app/
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "SpringBoot-CRUD-Operations.jar"]
